name: Github Pages Astro CI

on:
  push:
    branches: [master]  # Or main, or your branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Or your preferred Node.js version
          cache: 'npm' # Cache dependencies

      - name: Install dependencies
        run: npm install # Or yarn install if you use Yarn

      - name: Build your site
        run: npm run build # Or yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist # Or the directory your Astro build outputs to (e.g., ./public)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2